# Travis CI configuration file for psycopg2

dist: trusty
sudo: required
language: python

python:
  - 2.7
  - 3.6
  - 2.6
  - 3.5
  - 3.4
  - 3.3
  - 3.2

install:
  - wget -O - http://initd.org/psycopg/upload/postgresql/postgresql-9.1.tar.bz2
    | sudo tar xjf - -C /usr/lib/postgresql
  - python setup.py build_ext --pg-config=/usr/lib/postgresql/9.1/bin/pg_config install
  - sudo scripts/travis_prepare.sh

script:
  - scripts/travis_test.sh

notifications:
  email: false
